import type { CSSProperties } from "react";

export const styles = {
  title: {
    color: "var(--ink)",
    fontSize: 12.5,
    fontWeight: 600,
    marginBottom: 10,
  },
  sectionTitle: {
    color: "var(--ink-2)",
    fontSize: 10.5,
    fontWeight: 700,
    margin: "14px 0 8px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    marginBottom: 10,
  },
  grid: {
    display: "grid",
    gap: "8px 10px",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  },
  label: {
    color: "var(--ink-3)",
    fontSize: 10.5,
    fontWeight: 600,
  },
  input: {
    background: "var(--panel)",
    border: "1px solid var(--line)",
    borderRadius: 6,
    color: "var(--ink)",
    font: "inherit",
    fontSize: 12,
    padding: "6px 10px",
    width: "100%",
  },
  monoInput: {
    fontFamily: '"SF Mono", monospace',
    fontSize: 11,
  },
  hint: {
    color: "var(--ink-3)",
    fontSize: 10.5,
    marginTop: 1,
  },
  segment: {
    display: "flex",
    flexWrap: "wrap",
    gap: 5,
  },
  segmentButton: {
    background: "var(--panel)",
    border: "1px solid var(--line)",
    borderRadius: 6,
    color: "var(--ink-2)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 11,
    fontWeight: 400,
    padding: "5px 10px",
  },
  segmentButtonActive: {
    background: "var(--accent-soft)",
    border: "1px solid var(--accent)",
    color: "var(--accent)",
    fontWeight: 600,
  },
  toggle: {
    alignItems: "center",
    background: "transparent",
    border: 0,
    color: "var(--ink-2)",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 10.5,
    fontWeight: 700,
    margin: "14px 0 8px",
    padding: 0,
    textAlign: "left",
  },
  checks: {
    display: "flex",
    flexWrap: "wrap",
    gap: 7,
    margin: "2px 0 10px",
  },
  checkLabel: {
    alignItems: "center",
    background: "var(--panel)",
    border: "1px solid var(--line)",
    borderRadius: 6,
    color: "var(--ink-2)",
    display: "inline-flex",
    fontSize: 11,
    gap: 6,
    padding: "5px 9px",
  },
  actions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    justifyContent: "flex-end",
    marginTop: 4,
  },
  engineRow: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
  },
  engineButton: {
    background: "var(--panel)",
    border: "1px solid var(--line)",
    borderRadius: 8,
    color: "var(--ink-2)",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    fontFamily: "inherit",
    gap: 4,
    minHeight: 82,
    padding: "9px 10px",
    textAlign: "left",
  },
  engineButtonActive: {
    background: "var(--accent-soft)",
    border: "1px solid var(--accent)",
    boxShadow: "inset 0 0 0 1px var(--accent)",
    color: "var(--ink)",
  },
  engineSelectButton: {
    background: "transparent",
    border: 0,
    color: "inherit",
    cursor: "pointer",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    font: "inherit",
    gap: 4,
    padding: 0,
    textAlign: "left",
    width: "100%",
  },
  engineName: {
    color: "var(--ink)",
    fontSize: 12,
    fontWeight: 700,
  },
  engineDesc: {
    color: "var(--ink-3)",
    fontSize: 10.5,
    lineHeight: 1.45,
  },
  engineStatus: {
    fontSize: 10,
    fontWeight: 700,
    marginTop: "auto",
  },
  providerGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  providerGroupLabel: {
    color: "var(--ink-3)",
    fontSize: 10,
    fontWeight: 700,
  },
  providerPlaceholder: {
    background: "var(--bg)",
    border: "1px solid var(--line)",
    borderRadius: 6,
    color: "var(--ink-3)",
    display: "inline-flex",
    fontSize: 11,
    padding: "5px 10px",
  },
  chipBadge: {
    color: "var(--green)",
    fontSize: 9.5,
    fontWeight: 700,
    marginLeft: 4,
  },
  nativeStatus: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    fontSize: 11,
    fontWeight: 600,
    gap: 6,
    margin: "2px 0 10px",
  },
  nativeStatusHelp: {
    flexBasis: "100%",
    fontWeight: 400,
    lineHeight: 1.45,
  },
  nativeStatusPath: {
    flexBasis: "100%",
    fontWeight: 400,
    lineHeight: 1.45,
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  statusLink: {
    background: "transparent",
    border: 0,
    color: "var(--accent)",
    cursor: "pointer",
    font: "inherit",
    fontWeight: 700,
    padding: 0,
    textDecoration: "underline",
  },
  saveWhy: {
    color: "var(--ink-3)",
    fontSize: 10.5,
    marginRight: "auto",
  },
  saveWarning: {
    color: "var(--amber-ink)",
    fontSize: 10.5,
    marginRight: "auto",
  },
  error: {
    color: "var(--red)",
    fontSize: 11,
    marginTop: 8,
    textAlign: "right",
  },
} satisfies Record<string, CSSProperties>;
