import type { CSSProperties } from "react";

export const styles = {
  root: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    maxWidth: 760,
  },
  header: {
    alignItems: "flex-start",
    gap: 16,
    justifyContent: "space-between",
    marginBottom: 0,
  },
  headerCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    minWidth: 0,
  },
  description: {
    color: "var(--ink-3)",
    fontSize: 11.5,
    lineHeight: 1.5,
    maxWidth: 620,
  },
  switchGroup: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 8,
  },
  switchStatus: {
    color: "var(--ink-2)",
    fontSize: 11,
    whiteSpace: "nowrap",
  },
  switch: {
    border: 0,
    borderRadius: 999,
    cursor: "pointer",
    height: 24,
    padding: 2,
    transition: "background 120ms ease",
    width: 42,
  },
  switchKnob: {
    background: "white",
    borderRadius: "50%",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.3)",
    display: "block",
    height: 20,
    transition: "transform 120ms ease",
    width: 20,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  label: {
    color: "var(--ink-2)",
    fontSize: 11,
    fontWeight: 600,
  },
  input: {
    background: "var(--panel)",
    border: "1px solid var(--line)",
    borderRadius: 6,
    color: "var(--ink)",
    fontFamily: '"SF Mono", monospace',
    fontSize: 11.5,
    padding: "7px 10px",
    width: "100%",
  },
  // The active-project select uses proportional text because project names are human-readable,
  // unlike relay URLs or tokens. Match `input` sizing and borders except for fontFamily.
  selectInput: {
    background: "var(--panel)",
    border: "1px solid var(--line)",
    borderRadius: 6,
    color: "var(--ink)",
    fontSize: 11.5,
    padding: "7px 10px",
    width: "100%",
  },
  hint: {
    color: "var(--ink-3)",
    fontSize: 10.5,
    lineHeight: 1.45,
  },
  currentServingRow: {
    alignItems: "baseline",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  currentServingLabel: {
    color: "var(--ink-2)",
    fontSize: 11,
    fontWeight: 600,
  },
  currentServingValue: {
    color: "var(--ink)",
    fontSize: 12.5,
    fontWeight: 650,
  },
  mismatchBanner: {
    alignItems: "center",
    border: "1px solid var(--amber)",
    borderRadius: 7,
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    padding: "9px 12px",
  },
  mismatchText: {
    color: "var(--amber-ink)",
    flex: 1,
    fontSize: 11.5,
    lineHeight: 1.5,
    minWidth: 200,
  },
  switchNotice: {
    alignItems: "center",
    border: "1px solid var(--amber)",
    borderRadius: 7,
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    padding: "9px 12px",
  },
  switchNoticeText: {
    color: "var(--amber-ink)",
    flex: 1,
    fontSize: 11.5,
    lineHeight: 1.5,
    minWidth: 200,
  },
  error: {
    color: "var(--red)",
    fontSize: 11,
    lineHeight: 1.45,
  },
  section: {
    border: "1px solid var(--line)",
    borderRadius: 8,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 14,
    transition: "opacity 120ms ease",
  },
  sectionHeader: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  sectionTitle: {
    color: "var(--ink)",
    fontSize: 12.5,
    fontWeight: 650,
  },
  pairingActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  qrWrap: {
    alignItems: "center",
    alignSelf: "flex-start",
    background: "white",
    border: "1px solid var(--line)",
    borderRadius: 8,
    display: "flex",
    justifyContent: "center",
    // Keep the QR render container at least 240×240 CSS px (pinned value).
    minWidth: 240,
    minHeight: 240,
    padding: 8,
  },
  pairingStatus: {
    color: "var(--ink-2)",
    fontSize: 11,
  },
  deviceList: {
    display: "flex",
    flexDirection: "column",
    gap: 7,
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  deviceRow: {
    alignItems: "center",
    border: "1px solid var(--line)",
    borderRadius: 7,
    display: "flex",
    gap: 12,
    padding: "10px 12px",
  },
  deviceBody: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: 3,
    minWidth: 0,
  },
  deviceName: {
    color: "var(--ink)",
    fontSize: 12.5,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  deviceMeta: {
    color: "var(--ink-3)",
    fontSize: 10.5,
    lineHeight: 1.4,
  },
  empty: {
    color: "var(--ink-3)",
    fontSize: 12,
    padding: "12px 0 4px",
  },
  diagnostics: {
    borderTop: "1px solid var(--line)",
    paddingTop: 10,
  },
  diagnosticsSummary: {
    color: "var(--ink-2)",
    cursor: "pointer",
    fontSize: 11.5,
    fontWeight: 600,
  },
  diagnosticsBody: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    paddingTop: 8,
  },
  diagnosticsGrid: {
    display: "grid",
    gap: "4px 14px",
    gridTemplateColumns: "minmax(0, 1fr) auto",
  },
  diagnosticsName: {
    color: "var(--ink-3)",
    fontFamily: '"SF Mono", monospace',
    fontSize: 10,
    overflowWrap: "anywhere",
  },
  diagnosticsValue: {
    color: "var(--ink-2)",
    fontFamily: '"SF Mono", monospace',
    fontSize: 10,
    overflowWrap: "anywhere",
    textAlign: "right",
  },
} satisfies Record<string, CSSProperties>;
